# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
# To update to all latest tagged versions run:
#     pre-commit autoupdate
# Manually run all hooks
#     pre-commit run -a
# Install tools on mac
# brew install pre-commit gawk terraform-docs tflint trivy coreutils checkov terrascan shellcheck
# npm install -g markdown-link-check
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.100.0
  hooks:
    #- id: infracost_breakdown
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_trivy
    - id: terraform_checkov
    #- id: terrascan
    #  args:
    #  - --args=-"-non-recursive"
    #  - --args="-v"
    #  #- --args="-c .terrascan.toml"
    #- id: tfupdate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: trailing-whitespace
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
    - id: shellcheck
    #- id: markdown-link-check
# - repo: https://github.com/igorshubovych/markdownlint-cli
#   rev: v0.23.2
#   hooks:
#     - id: markdownlint
#       args: [
#         "--config=.mdlrc"
#       ]
#default_stages: [commit, push]
