# https://terraform-docs.io/user-guide/configuration/

# Testing
# terraform-docs markdown . --recursive --output-file test.md

formatter: markdown
version: "0.20"
footer-from: ""
header-from: main.tf
#output:
#  file: README.md
#  mode: inject
#  template: |-
#      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
#      {{ .Content }}
#      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
recursive:
  enabled: false
  path: modules
#  path: examples
sections:
  hide: []
  show: []
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
sort:
  enabled: true
  by: name

content: |-
  {{ .Header }}

  ## Usage

  Basic usage of this module is as follows:

  ```hcl
  module "example" {
  {{"    " -}} source = "wisk-aero-oss/<module-name>/google"
  {{"    " -}} # Recommend pinning every module to a specific version
  {{"    " -}} # version = "x.x.x"
  {{- if .Module.RequiredInputs }}
    {{"\n    " -}} # Required variables
    {{- range .Module.RequiredInputs }}
      {{"    " -}}{{ .Name }} ={{ .GetValue }}
    {{- end }}
  {{- end }}
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
